apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet # StatefulSets provide stable storage across pod restarts.
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: set_value_here
            - name: POSTGRES_PASSWORD
              value: set_value_here
            - name: POSTGRES_DB
              value: backend
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  # PersistentVolumeClaim ensures that event metadata survives pod failures or cluster restarts.
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi